import argparse
import json
from pathlib import Path


def default_template_path():
    return Path(__file__).resolve().parents[1] / "assets" / "templates" / "yizhan-report-template.html"


def render_html_report(template_path, registry_path, output_path):
    template = Path(template_path).read_text(encoding="utf-8")
    registry = json.loads(Path(registry_path).read_text(encoding="utf-8"))
    payload = json.dumps(registry, ensure_ascii=False, separators=(",", ":"))
    html = template.replace("__REPORT_DATA_JSON__", payload)
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(html, encoding="utf-8")
    return output


def main():
    parser = argparse.ArgumentParser(description="Render 生涯翼站 HTML report from registry JSON.")
    parser.add_argument("--registry", required=True, help="Registry JSON generated by build_registry.py.")
    parser.add_argument("--out", required=True, help="Output HTML path.")
    parser.add_argument("--template", default=str(default_template_path()), help="HTML template path.")
    args = parser.parse_args()
    print(render_html_report(args.template, args.registry, args.out))


if __name__ == "__main__":
    main()
